# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dev_Work_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_elapsed_dev', models.IntegerField(blank=True, default=None, null=True, verbose_name='Time elapsed')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.Developer')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='developer',
        ),
        migrations.AddField(
            model_name='dev_work_task',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='developers',
            field=models.ManyToManyField(through='task_manager.Dev_Work_Task', to='task_manager.Developer'),
        ),
    ]
